site_name: ''
site_url: https://dominolowcode.github.io/
nav:
   - index.md
   - Getting started:
     - Overview: getting-started/index.md
     - Loading data:
       - CSV to Pandas: getting-started/loading-data/csv.md
       - Snowflake to Pandas: getting-started/loading-data/snowflake.md
       - Redshift to Pandas: getting-started/loading-data/redshift.md
       - SQL with editor to Pandas: getting-started/loading-data/sql.md
     - Transforming data:
       - Filter NaN values: getting-started/transform.md
     - Visualizing data:
       - Scatter plot with Plotly: getting-started/viz/scatter.md
     - Apps:
       - App creation: getting-started/app/create.md
       - Deploy an App: getting-started/app/deploy.md
       - Upload data to an App: getting-started/app/upload.md
     - Code snippets:
       - Code snippets: getting-started/code-snippets.md
   - install.md
theme:
  name: material
  favicon: favicon.png
  logo: https://dominodatalab.github.io/api-docs/logo.png
  features:
    - content.tabs.link
    - navigation.expand
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
repo_url: https://github.com/dominodatalab/low-code-jupyter-docs/
repo_name: low-code-jupyter-docs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
redirects:
  'install.md': 'index.md'
