site_name: ''
site_url: https://dominolowcode.github.io/
nav:
    - index.md
    - Installing:  install.md
    - Settings:  settings.md
    - Loading Data:
      - Loading Data from CSV: loading-data/csv.md
      - Loading Data with SQL: loading-data/sql.md
      - Loading Data from Snowflake: loading-data/snowflake.md
      - Loading Data from Redshift: loading-data/redshift.md
      - Loading Data from BigQuery: loading-data/bigquery.md
      - Loading Data from S3: loading-data/s3.md
    - Transformation:
      - Filter NaN values: transform/filter-nan.md
    - Visualization:
      - Plots with Plotly: visualization/plotly.md
    - Apps:
      - App creation: app/create.md
      - Deploy an App: app/deploy.md
      - Upload data to an App: app/upload.md
    - Code Snippets:
      - Code Snippets: snippets/code-snippets.md
      - Using Snippets: snippets/snippets-using.md
      - Adding Snippets: snippets/snippets-adding.md
      - Editing Snippets: snippets/snippets-editing.md
theme:
  name: material
  favicon: favicon.png
  logo: https://dominodatalab.github.io/api-docs/logo.png
  features:
    - content.tabs.link
    - navigation.expand
  custom_dir: overrides
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
repo_url: https://github.com/dominodatalab/low-code-jupyter-docs/
repo_name: low-code-jupyter-docs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - redirects:
        redirect_maps:
            'docs/install.md': 'docs/index.md'
            'install.md': 'index.md'
            'docs/install.md': 'index.md'
            'data-from-csv-in-python.md': 'loading-data/csv.md'
            'data-from-sql-in-python.md': 'loading-data/sql.md'
            'connect-to-snowflake-in-python.md': 'loading-data/snowflake.md'
            'connect-to-redshift-in-python.md': 'loading-data/redshift.md'
            'connect-to-bigquery-in-python.md': 'loading-data/bigquery.md'
            'connect-to-s3-in-python.md': 'loading-data/s3.md'
