name: Build, Check & Deploy
on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Build site
        run: |
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: site/
  check-links:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/linkchecker/linkchecker:latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site/
      - run: linkchecker site/index.html
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [check-links]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Install Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.x
  #     - name: Install Python dependencies
  #       run: |
  #         pip install -r requirements.txt
  #     - name: Test deploy
  #       run: mkdocs gh-deploy --force --clean --verbose
